#!/usr/bin/env python3
"""
Data Lifecycle Manager for lean-hooks.
Handles:
  - MEMORY.md rotation (archive + reset when too large)
  - SQLite session log archiving (export to archive/ + trim)
  - ERROR.md pruning (remove entries older than max_age)

Configured via lean-hooks.toml [data_lifecycle] section.

Usage:
    python data-lifecycle.py [--dry-run] [--force]
"""

import json
import os
import sqlite3
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# --- defaults ---
DEFAULT_MAX_MEMORY_KB = 64       # rotate MEMORY.md if >64KB
DEFAULT_MAX_SESSION_DAYS = 90    # archive sessions older than 90 days
DEFAULT_MAX_ERROR_DAYS = 30      # prune ERRORS.md entries older than 30 days
DEFAULT_ARCHIVE_DIR = "archive"

# --- path resolution ---
SCRIPT_DIR = Path(__file__).resolve().parent
HARNESS_ROOT = Path(os.environ.get("HARNESS_ROOT", SCRIPT_DIR.parent)).resolve()
CONFIG_DIR = HARNESS_ROOT / "config" if (HARNESS_ROOT / "config").exists() else HARNESS_ROOT


def load_toml_config():
    """Load the toml config file if available, else return empty dict."""
    cfg = {}
    for candidate in [
        CONFIG_DIR / "lean-hooks.toml",
        HARNESS_ROOT / "lean-hooks.toml",
        Path.home() / ".claude" / "lean-hooks.toml",
    ]:
        if candidate.exists():
            # Use json-compatible approach — TOML library may not be installed,
            # so we parse a subset manually or fallback to defaults
            try:
                import tomllib
                with open(candidate, "rb") as f:
                    cfg = tomllib.load(f)
            except (ImportError, Exception):
                # No tomllib (Python <3.11), try tomli
                try:
                    import tomli
                    with open(candidate, "rb") as f:
                        cfg = tomli.load(f)
                except (ImportError, Exception):
                    pass
            break
    return cfg


def get_config(key, default):
    cfg = load_toml_config()
    lc = cfg.get("data_lifecycle", {})
    return lc.get(key, default)


def rotate_memory(memory_dir: Path, dry_run: bool = False):
    """Rotate MEMORY.md if it exceeds max size."""
    max_kb = get_config("max_memory_kb", DEFAULT_MAX_MEMORY_KB)
    memory_file = memory_dir / "MEMORY.md"
    if not memory_file.exists():
        return

    size_kb = memory_file.stat().st_size / 1024
    if size_kb <= max_kb:
        return

    archive_dir = memory_dir / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
    archive_dir.mkdir(parents=True, exist_ok=True)

    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    archive_name = f"MEMORY.{date_str}.md"
    archive_path = archive_dir / archive_name

    if dry_run:
        print(f"[data-lifecycle] DRY-RUN: would rotate {memory_file.name} ({size_kb:.1f}KB > {max_kb}KB) -> {archive_path}")
        return

    shutil.copy2(str(memory_file), str(archive_path))
    # Reset MEMORY.md to header only
    memory_file.write_text("# Memory Index\n\n> Auto-generated by harness. Rotated on " + date_str + "\n\n", encoding="utf-8")
    print(f"[data-lifecycle] Rotated {memory_file.name} ({size_kb:.1f}KB) -> {archive_path}")


def archive_sessions(db_path: Path, dry_run: bool = False):
    """Archive and delete old session log entries."""
    max_days = get_config("max_session_days", DEFAULT_MAX_SESSION_DAYS)
    archive_dir = db_path.parent / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
    archive_dir.mkdir(parents=True, exist_ok=True)

    if not db_path.exists():
        return

    cutoff = int(time.time()) - max_days * 86400

    conn = sqlite3.connect(str(db_path))
    try:
        cursor = conn.execute(
            "SELECT id, project, created_at, summary, files_touched FROM session_logs WHERE created_epoch < ?",
            (cutoff,),
        )
        rows = cursor.fetchall()

        if not rows:
            return

        if dry_run:
            print(f"[data-lifecycle] DRY-RUN: would archive {len(rows)} session logs older than {max_days}d")
            return

        # Export to archive file
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        archive_file = archive_dir / f"session_logs.{date_str}.jsonl"
        with open(archive_file, "w", encoding="utf-8") as af:
            for row in rows:
                record = {
                    "id": row[0], "project": row[1], "created_at": row[2],
                    "summary": row[3], "files_touched": row[4],
                }
                af.write(json.dumps(record, ensure_ascii=False) + "\n")

        # Delete archived rows
        conn.execute("DELETE FROM session_logs WHERE created_epoch < ?", (cutoff,))
        conn.commit()
        print(f"[data-lifecycle] Archived {len(rows)} sessions -> {archive_file}")
    finally:
        conn.close()


def prune_errors(errors_file: Path, dry_run: bool = False):
    """Prune old entries from ERRORS.md."""
    max_days = get_config("max_error_days", DEFAULT_MAX_ERROR_DAYS)
    if not errors_file.exists():
        return

    # Simple pruning: if file is >1MB, rotate it entirely
    size_kb = errors_file.stat().st_size / 1024
    if size_kb > 1024:
        archive_dir = errors_file.parent / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
        archive_dir.mkdir(parents=True, exist_ok=True)
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        if dry_run:
            print(f"[data-lifecycle] DRY-RUN: would rotate {errors_file.name} ({size_kb:.0f}KB)")
            return
        shutil.copy2(str(errors_file), str(archive_dir / f"ERRORS.{date_str}.md"))
        # Keep only header
        errors_file.write_text(
            "# lean-hooks Error Log\n\n> Auto-generated. Rotated on " + date_str + "\n\n"
            "| Timestamp | Hook | Duration | Exit Code | Error |\n"
            "|-----------|------|----------|-----------|-------|\n",
            encoding="utf-8",
        )
        print(f"[data-lifecycle] Rotated ERRORS.md ({size_kb:.0f}KB) -> {archive_dir / f'ERRORS.{date_str}.md'}")


def main():
    import argparse
    parser = argparse.ArgumentParser(description="lean-hooks data lifecycle manager")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done without doing it")
    parser.add_argument("--force", action="store_true", help="Force rotation even if under threshold")
    args = parser.parse_args()

    memory_dir = Path(os.environ.get("MEMORY_DIR", str(CONFIG_DIR / "memory")))
    db_path = Path(os.environ.get("MEM_DB", str(HARNESS_ROOT / "data" / "claude-mem" / "claude-mem.db")))
    errors_file = Path(os.environ.get("ERRORS_FILE", str(CONFIG_DIR / "ERRORS.md")))

    actions = 0

    # MEMORY.md rotation
    md_dir = memory_dir
    if md_dir.exists():
        rotate_memory(md_dir, args.dry_run)
        actions += 1

    # Session log archive
    if db_path.exists():
        archive_sessions(db_path, args.dry_run)
        actions += 1

    # ERROR.md prune
    if errors_file.exists():
        prune_errors(errors_file, args.dry_run)
        actions += 1

    if actions == 0:
        print("[data-lifecycle] No data lifecycle actions needed")
    elif args.dry_run:
        print("[data-lifecycle] DRY-RUN complete — no changes made")


if __name__ == "__main__":
    main()