#!/usr/bin/env python3
"""
Data Lifecycle Manager for lean-hooks.

Handles:
  - MEMORY.md rotation (archive + reset when too large)
  - SQLite session log archiving (export to archive/ + trim)
  - ERROR.md pruning (remove entries older than max_age)
  - Observation contradiction detection + invalidation
  - Observation temporal expiration
  - Observation quality scoring
  - Observation density consolidation

Configured via lean-hooks.toml [data_lifecycle] section.

Usage:
    python data-lifecycle.py [--dry-run] [--force]
"""

import json
import os
import re
import sqlite3
import shutil
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

# --- defaults ---
DEFAULT_MAX_MEMORY_KB = 64       # rotate MEMORY.md if >64KB
DEFAULT_MAX_SESSION_DAYS = 90    # archive sessions older than 90 days
DEFAULT_MAX_ERROR_DAYS = 30      # prune ERRORS.md entries older than 30 days
DEFAULT_ARCHIVE_DIR = "archive"

# --- observation evolution defaults ---
DEFAULT_OBS_TTL = {
    "decision": 0,     # never expires
    "change": 180,
    "bugfix": 90,
    "feature": 90,
    "discovery": 60,
    "refactor": 90,
    "consolidated": 0,  # never expires (curated)
}
DEFAULT_QUALITY_BY_TYPE = {
    "decision": 0.9,
    "feature": 0.7,
    "bugfix": 0.6,
    "change": 0.5,
    "discovery": 0.4,
    "refactor": 0.5,
    "consolidated": 0.8,
}
DEFAULT_JACCARD_THRESHOLD = 0.5
DEFAULT_MIN_HOURS_APART = 24
DEFAULT_CONSOLIDATION_MIN_GROUP = 3
DEFAULT_QUALITY_DECAY_RATE = 0.3
DEFAULT_SESSION_TTL_NO_SUBSTANCE = 30
DEFAULT_SESSION_TTL_SUBSTANCE = 90

# --- path resolution ---
SCRIPT_DIR = Path(__file__).resolve().parent
# In claude-ecosystem layout: script is at <root>/config/harness/data-lifecycle.py
# SCRIPT_DIR.parent = <root>/config, SCRIPT_DIR.parent.parent = <root>
_HARNESS_PARENT = SCRIPT_DIR.parent
if _HARNESS_PARENT.name == "config":
    HARNESS_ROOT = _HARNESS_PARENT.parent
else:
    HARNESS_ROOT = Path(os.environ.get("HARNESS_ROOT", str(_HARNESS_PARENT))).resolve()
CONFIG_DIR = HARNESS_ROOT / "config" if (HARNESS_ROOT / "config").exists() else HARNESS_ROOT


def load_toml_config():
    cfg = {}
    for candidate in [
        CONFIG_DIR / "lean-hooks.toml",
        HARNESS_ROOT / "lean-hooks.toml",
        Path.home() / ".claude" / "lean-hooks.toml",
    ]:
        if candidate.exists():
            try:
                import tomllib
                with open(candidate, "rb") as f:
                    cfg = tomllib.load(f)
            except (ImportError, Exception):
                try:
                    import tomli
                    with open(candidate, "rb") as f:
                        cfg = tomli.load(f)
                except (ImportError, Exception):
                    pass
            break
    return cfg


def get_config(key, default):
    cfg = load_toml_config()
    lc = cfg.get("data_lifecycle", {})
    return lc.get(key, default)


def get_ttl_days(obs_type):
    ttl_overrides = get_config("obs_ttl_overrides", {})
    if obs_type in ttl_overrides:
        return ttl_overrides[obs_type]
    return DEFAULT_OBS_TTL.get(obs_type, 90)


# ===================== Existing functions (unchanged) =====================

def rotate_memory(memory_dir: Path, dry_run: bool = False):
    max_kb = get_config("max_memory_kb", DEFAULT_MAX_MEMORY_KB)
    memory_file = memory_dir / "MEMORY.md"
    if not memory_file.exists():
        return
    size_kb = memory_file.stat().st_size / 1024
    if size_kb <= max_kb:
        return
    archive_dir = memory_dir / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
    archive_dir.mkdir(parents=True, exist_ok=True)
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    archive_name = f"MEMORY.{date_str}.md"
    archive_path = archive_dir / archive_name
    if dry_run:
        print(f"[data-lifecycle] DRY-RUN: would rotate {memory_file.name} ({size_kb:.1f}KB > {max_kb}KB) -> {archive_path}")
        return
    shutil.copy2(str(memory_file), str(archive_path))
    memory_file.write_text("# Memory Index\n\n> Auto-generated by harness. Rotated on " + date_str + "\n\n", encoding="utf-8")
    print(f"[data-lifecycle] Rotated {memory_file.name} ({size_kb:.1f}KB) -> {archive_path}")


def archive_sessions(db_path: Path, dry_run: bool = False):
    max_days = get_config("max_session_days", DEFAULT_MAX_SESSION_DAYS)
    archive_dir = db_path.parent / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
    archive_dir.mkdir(parents=True, exist_ok=True)
    if not db_path.exists():
        return
    cutoff = int(time.time()) - max_days * 86400
    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as e:
        print(f"data-lifecycle: sqlite3 connect error: {e}", file=sys.stderr)
        return
    try:
        cursor = conn.execute(
            "SELECT id, project, created_at, summary, files_touched FROM session_logs WHERE created_epoch < ?",
            (cutoff,),
        )
        rows = cursor.fetchall()
        if not rows:
            return
        if dry_run:
            print(f"[data-lifecycle] DRY-RUN: would archive {len(rows)} session logs older than {max_days}d")
            return
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        archive_file = archive_dir / f"session_logs.{date_str}.jsonl"
        with open(archive_file, "w", encoding="utf-8") as af:
            for row in rows:
                record = {"id": row[0], "project": row[1], "created_at": row[2], "summary": row[3], "files_touched": row[4]}
                af.write(json.dumps(record, ensure_ascii=False) + "\n")
        conn.execute("DELETE FROM session_logs WHERE created_epoch < ?", (cutoff,))
        conn.commit()
        print(f"[data-lifecycle] Archived {len(rows)} sessions -> {archive_file}")
    finally:
        conn.close()


def prune_errors(errors_file: Path, dry_run: bool = False):
    max_days = get_config("max_error_days", DEFAULT_MAX_ERROR_DAYS)
    if not errors_file.exists():
        return
    size_kb = errors_file.stat().st_size / 1024
    if size_kb > 1024:
        archive_dir = errors_file.parent / get_config("archive_dir", DEFAULT_ARCHIVE_DIR)
        archive_dir.mkdir(parents=True, exist_ok=True)
        date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
        if dry_run:
            print(f"[data-lifecycle] DRY-RUN: would rotate {errors_file.name} ({size_kb:.0f}KB)")
            return
        shutil.copy2(str(errors_file), str(archive_dir / f"ERRORS.{date_str}.md"))
        errors_file.write_text(
            "# lean-hooks Error Log\n\n> Auto-generated. Rotated on " + date_str + "\n\n"
            "| Timestamp | Hook | Duration | Exit Code | Error |\n"
            "|-----------|------|----------|-----------|-------|\n",
            encoding="utf-8",
        )
        print(f"[data-lifecycle] Rotated ERRORS.md ({size_kb:.0f}KB) -> {archive_dir / f'ERRORS.{date_str}.md'}")


# ===================== New: Evolution functions =====================

def _tokenize(text):
    """Lowercase, strip punctuation, split into word set for Jaccard."""
    words = re.sub(r'[^\w\s]', ' ', text.lower()).split()
    return set(words)


def _jaccard(set_a, set_b):
    if not set_a or not set_b:
        return 0.0
    return len(set_a & set_b) / len(set_a | set_b)


def detect_contradictions(db_path: Path, dry_run: bool = False):
    """Find and mark contradicted/superseded observations.

    For each group of same-type same-project observations with title
    Jaccard >= threshold and >24h apart: older ones get invalidated,
    newer ones get supersedes_id pointing to the oldest in the group.
    """
    threshold = get_config("contradiction_jaccard_threshold", DEFAULT_JACCARD_THRESHOLD)
    min_hours = get_config("contradiction_min_hours_apart", DEFAULT_MIN_HOURS_APART)
    min_seconds = min_hours * 3600

    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as e:
        print(f"data-lifecycle: sqlite3 connect error: {e}", file=sys.stderr)
        return
    try:
        cur = conn.execute(
            "SELECT id, type, project, title, created_at_epoch, invalidated_at_epoch "
            "FROM observations WHERE invalidated_at_epoch IS NULL "
            "ORDER BY type, project, created_at_epoch ASC"
        )
        rows = cur.fetchall()
        if not rows:
            return

        # Group by (type, project)
        groups = {}
        for row in rows:
            key = (row[1], row[2])
            groups.setdefault(key, []).append(row)

        invalidated = 0
        chained = 0
        now_epoch = int(time.time())

        for (obs_type, project), group in groups.items():
            if len(group) < 2:
                continue

            # Pre-tokenize titles
            tokenized = [(row, _tokenize(row[3] or "")) for row in group]

            # For each pair, check if titles are similar (contradiction candidates)
            # Use a simple cluster approach: Union-Find on Jaccard similarity
            parent = {row[0]: row[0] for row in group}

            def find(x):
                while parent[x] != x:
                    parent[x] = parent[parent[x]]
                    x = parent[x]
                return x

            def union(a, b):
                ra, rb = find(a), find(b)
                if ra != rb:
                    parent[ra] = rb

            for i in range(len(tokenized)):
                for j in range(i + 1, len(tokenized)):
                    row_a, tok_a = tokenized[i]
                    row_b, tok_b = tokenized[j]
                    sim = _jaccard(tok_a, tok_b)
                    if sim >= threshold and (row_b[4] - row_a[4]) >= min_seconds:
                        union(row_a[0], row_b[0])

            # Build clusters
            clusters = {}
            for row in group:
                root = find(row[0])
                clusters.setdefault(root, []).append(row)

            for root, cluster in clusters.items():
                if len(cluster) < 2:
                    continue
                # Sort by time: oldest first
                cluster.sort(key=lambda r: r[4])
                oldest = cluster[0]
                newest = cluster[-1]

                if dry_run:
                    print(f"[data-lifecycle] DRY-RUN: contradiction cluster (type={obs_type}, project={project}): "
                          f"{len(cluster)} observations, IDs {[r[0] for r in cluster]}")
                    continue

                # Invalidate all but the newest, chain newest to oldest
                for row in cluster[:-1]:
                    conn.execute(
                        "UPDATE observations SET invalidated_at_epoch = ? WHERE id = ? AND invalidated_at_epoch IS NULL",
                        (now_epoch, row[0]),
                    )
                    invalidated += 1

                # Set supersedes_id on newest pointing to oldest in chain
                conn.execute(
                    "UPDATE observations SET supersedes_id = ? WHERE id = ? AND supersedes_id IS NULL",
                    (oldest[0], newest[0]),
                )
                chained += 1

        if invalidated or chained:
            conn.commit()
            if not dry_run:
                print(f"[data-lifecycle] Contradiction detection: invalidated {invalidated}, chained {chained}")
    finally:
        conn.close()


def expire_observations(db_path: Path, dry_run: bool = False):
    """Compute expiration timestamps and mark expired observations/session_logs."""
    now_epoch = int(time.time())

    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as e:
        print(f"data-lifecycle: sqlite3 connect error: {e}", file=sys.stderr)
        return
    try:
        # --- observations: compute expires_at_epoch for rows where NULL ---
        obs_rows = conn.execute(
            "SELECT id, type, created_at_epoch, expires_at_epoch, invalidated_at_epoch "
            "FROM observations WHERE invalidated_at_epoch IS NULL"
        ).fetchall()

        computed = 0
        for row in obs_rows:
            obs_id, obs_type, created, expires, invalidated = row
            if expires is not None:
                continue
            ttl_days = get_ttl_days(obs_type)
            if ttl_days == 0:
                continue  # never expires
            expires_epoch = created + ttl_days * 86400
            if not dry_run:
                conn.execute(
                    "UPDATE observations SET expires_at_epoch = ? WHERE id = ?",
                    (expires_epoch, obs_id),
                )
            computed += 1

        # Mark rows where expires_at_epoch has passed
        expired = conn.execute(
            "SELECT COUNT(*) FROM observations "
            "WHERE invalidated_at_epoch IS NULL AND expires_at_epoch IS NOT NULL AND expires_at_epoch <= ?",
            (now_epoch,),
        ).fetchone()[0]

        if expired > 0:
            if dry_run:
                print(f"[data-lifecycle] DRY-RUN: would expire {expired} observations")
            else:
                conn.execute(
                    "UPDATE observations SET invalidated_at_epoch = ? "
                    "WHERE invalidated_at_epoch IS NULL AND expires_at_epoch IS NOT NULL AND expires_at_epoch <= ?",
                    (now_epoch, now_epoch),
                )

        # --- session_logs: compute expires_at_epoch ---
        sl_rows = conn.execute(
            "SELECT id, has_substance, created_epoch, expires_at_epoch FROM session_logs WHERE expires_at_epoch IS NULL"
        ).fetchall()

        sl_computed = 0
        for row in sl_rows:
            sl_id, substance, created, expires = row
            ttl = DEFAULT_SESSION_TTL_SUBSTANCE if substance else DEFAULT_SESSION_TTL_NO_SUBSTANCE
            expires_epoch = created + ttl * 86400
            if not dry_run:
                conn.execute(
                    "UPDATE session_logs SET expires_at_epoch = ? WHERE id = ?",
                    (expires_epoch, sl_id),
                )
            sl_computed += 1

        # Mark expired session_logs (they don't have invalidated_at_epoch, just let archive_sessions handle them)
        sl_expired = conn.execute(
            "SELECT COUNT(*) FROM session_logs WHERE expires_at_epoch IS NOT NULL AND expires_at_epoch <= ?",
            (now_epoch,),
        ).fetchone()[0]

        if not dry_run:
            conn.commit()
            if computed or expired or sl_computed:
                parts = []
                if computed:
                    parts.append(f"computed TTL for {computed} observations")
                if expired:
                    parts.append(f"expired {expired} observations")
                if sl_computed:
                    parts.append(f"computed TTL for {sl_computed} session logs")
                print(f"[data-lifecycle] Expiration: {'; '.join(parts)}")
        else:
            parts = []
            if computed:
                parts.append(f"would compute TTL for {computed} observations")
            if expired:
                parts.append(f"would expire {expired} observations")
            if sl_computed:
                parts.append(f"would compute TTL for {sl_computed} session logs")
            if parts:
                print(f"[data-lifecycle] DRY-RUN: {'; '.join(parts)}")
    finally:
        conn.close()


def assign_quality_scores(db_path: Path, dry_run: bool = False):
    """Assign initial quality scores to observations and apply time decay."""
    decay_rate = get_config("quality_decay_rate", DEFAULT_QUALITY_DECAY_RATE)
    now_epoch = int(time.time())

    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as e:
        print(f"data-lifecycle: sqlite3 connect error: {e}", file=sys.stderr)
        return
    try:
        # --- Assign initial quality for rows at default (0.5) ---
        rows = conn.execute(
            "SELECT id, type, facts, narrative, quality_score, relevance_count "
            "FROM observations WHERE quality_score = 0.5"
        ).fetchall()

        assigned = 0
        for row in rows:
            obs_id, obs_type, facts, narrative, qs, rel_count = row
            base = DEFAULT_QUALITY_BY_TYPE.get(obs_type, 0.5)
            # Content richness bonus
            content_len = len(facts or "") + len(narrative or "")
            if content_len > 800:
                base = min(base + 0.1, 1.0)
            if not dry_run:
                conn.execute(
                    "UPDATE observations SET quality_score = ? WHERE id = ?",
                    (base, obs_id),
                )
            assigned += 1

        # --- Time decay for observations not recently accessed ---
        # Decay: quality_score *= (1 - decay_rate * days_since_access / 365)
        # Exempt if relevance_count > 5 (actively used)
        decay_rows = conn.execute(
            "SELECT id, quality_score, created_at_epoch, relevance_count "
            "FROM observations WHERE quality_score != 0.5 AND invalidated_at_epoch IS NULL"
        ).fetchall()

        decayed = 0
        for row in decay_rows:
            obs_id, qs, created, rel_count = row
            if rel_count and rel_count > 5:
                continue  # actively used, no decay
            days_old = (now_epoch - created) / 86400
            if days_old < 30:
                continue  # too new for decay
            decay_factor = 1 - decay_rate * min(days_old, 365) / 365
            new_qs = max(qs * decay_factor, 0.1)  # floor at 0.1
            if abs(new_qs - qs) > 0.01:
                if not dry_run:
                    conn.execute(
                        "UPDATE observations SET quality_score = ? WHERE id = ?",
                        (round(new_qs, 3), obs_id),
                    )
                decayed += 1

        # --- session_logs quality ---
        sl_rows = conn.execute(
            "SELECT id, has_substance, quality_score FROM session_logs WHERE quality_score = 0.5"
        ).fetchall()

        sl_assigned = 0
        for row in sl_rows:
            sl_id, substance, qs = row
            new_qs = 0.7 if substance else 0.1
            if not dry_run:
                conn.execute(
                    "UPDATE session_logs SET quality_score = ? WHERE id = ?",
                    (new_qs, sl_id),
                )
            sl_assigned += 1

        if not dry_run:
            conn.commit()
            parts = []
            if assigned:
                parts.append(f"scored {assigned} observations")
            if decayed:
                parts.append(f"decayed {decayed} observations")
            if sl_assigned:
                parts.append(f"scored {sl_assigned} session logs")
            if parts:
                print(f"[data-lifecycle] Quality scoring: {'; '.join(parts)}")
        else:
            parts = []
            if assigned:
                parts.append(f"would score {assigned} observations")
            if decayed:
                parts.append(f"would decay {decayed} observations")
            if sl_assigned:
                parts.append(f"would score {sl_assigned} session logs")
            if parts:
                print(f"[data-lifecycle] DRY-RUN: {'; '.join(parts)}")
    finally:
        conn.close()


def consolidate_observations(db_path: Path, dry_run: bool = False):
    """Consolidate groups of similar non-invalidated observations into one.

    Finds clusters of same-type same-project observations with title
    Jaccard >= threshold that are NOT already invalidated. For groups
    >= min_group_size: creates a single 'consolidated' observation,
    marks originals as invalidated, sets supersedes chain.
    """
    threshold = get_config("consolidation_jaccard_threshold", DEFAULT_JACCARD_THRESHOLD)
    min_group = get_config("consolidation_min_group_size", DEFAULT_CONSOLIDATION_MIN_GROUP)

    try:
        conn = sqlite3.connect(str(db_path))
    except sqlite3.Error as e:
        print(f"data-lifecycle: sqlite3 connect error: {e}", file=sys.stderr)
        return
    try:
        cur = conn.execute(
            "SELECT id, type, project, title, facts, narrative, created_at_epoch, "
            "       memory_session_id, concepts, files_read, files_modified, content_hash "
            "FROM observations WHERE invalidated_at_epoch IS NULL "
            "AND type != 'consolidated' "
            "ORDER BY type, project, created_at_epoch ASC"
        )
        rows = cur.fetchall()
        if not rows:
            return

        # Group by (type, project)
        groups = {}
        for row in rows:
            key = (row[1], row[2])
            groups.setdefault(key, []).append(row)

        consolidated_groups = 0
        originals_invalidated = 0

        for (obs_type, project), group in groups.items():
            if len(group) < min_group:
                continue

            # Cluster by title Jaccard
            tokenized = [(row, _tokenize(row[3] or "")) for row in group]
            parent = {row[0]: row[0] for row in group}

            def find(x):
                while parent[x] != x:
                    parent[x] = parent[parent[x]]
                    x = parent[x]
                return x

            def union(a, b):
                ra, rb = find(a), find(b)
                if ra != rb:
                    parent[ra] = rb

            for i in range(len(tokenized)):
                for j in range(i + 1, len(tokenized)):
                    row_a, tok_a = tokenized[i]
                    row_b, tok_b = tokenized[j]
                    if _jaccard(tok_a, tok_b) >= threshold:
                        union(row_a[0], row_b[0])

            clusters = {}
            for row in group:
                root = find(row[0])
                clusters.setdefault(root, []).append(row)

            now_epoch = int(time.time())
            now_iso = datetime.now(timezone.utc).isoformat()

            for root, cluster in clusters.items():
                if len(cluster) < min_group:
                    continue

                # Sort by creation time, newest last
                cluster.sort(key=lambda r: r[6])
                newest = cluster[-1]

                if dry_run:
                    print(f"[data-lifecycle] DRY-RUN: would consolidate {len(cluster)} observations "
                          f"(type={obs_type}, project={project}), IDs: {[r[0] for r in cluster]}")
                    consolidated_groups += 1
                    continue

                # Build consolidated content from newest observation
                superseded_ids = [r[0] for r in cluster[:-1]]
                facts = (newest[4] or "") + f"\n\nSupersedes: {', '.join(str(i) for i in superseded_ids)}"
                narrative = newest[5] or ""

                # Insert consolidated observation
                conn.execute(
                    "INSERT INTO observations "
                    "(memory_session_id, project, type, title, facts, narrative, "
                    " concepts, files_read, files_modified, created_at, created_at_epoch, "
                    " content_hash, quality_score, supersedes_id, expires_at_epoch) "
                    "VALUES (?, ?, 'consolidated', ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 0, NULL)",
                    (
                        newest[7],  # memory_session_id
                        project,
                        f"[consolidated] {newest[3] or 'untitled'}",
                        facts,
                        narrative,
                        newest[8],   # concepts
                        newest[9],   # files_read
                        newest[10],  # files_modified
                        now_iso,
                        now_epoch,
                        newest[11],  # content_hash (reuse from newest)
                        min(DEFAULT_QUALITY_BY_TYPE.get("consolidated", 0.8) + 0.1, 1.0),
                    ),
                )
                new_id = conn.execute("SELECT last_insert_rowid()").fetchone()[0]

                # Invalidate originals (all except newest)
                for row in cluster[:-1]:
                    conn.execute(
                        "UPDATE observations SET invalidated_at_epoch = ? WHERE id = ?",
                        (now_epoch, row[0]),
                    )
                    originals_invalidated += 1

                # Set supersedes_id on newest original → point to consolidated
                conn.execute(
                    "UPDATE observations SET invalidated_at_epoch = ?, supersedes_id = ? WHERE id = ?",
                    (now_epoch, new_id, newest[0]),
                )
                originals_invalidated += 1

                consolidated_groups += 1

        if consolidated_groups:
            if not dry_run:
                conn.commit()
                print(f"[data-lifecycle] Consolidation: {consolidated_groups} groups, "
                      f"{originals_invalidated} originals invalidated")
            else:
                print(f"[data-lifecycle] DRY-RUN: would consolidate {consolidated_groups} groups")
    finally:
        conn.close()


# ===================== Main =====================

def main():
    import argparse
    parser = argparse.ArgumentParser(description="lean-hooks data lifecycle manager")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be done without doing it")
    parser.add_argument("--force", action="store_true", help="Force rotation even if under threshold")
    parser.add_argument("--skip-legacy", action="store_true", help="Skip legacy rotation/archive/prune steps")
    args = parser.parse_args()

    memory_dir = Path(os.environ.get("MEMORY_DIR", str(CONFIG_DIR / "memory")))
    db_path = Path(os.environ.get("MEM_DB", str(HARNESS_ROOT / "data" / "claude-mem" / "claude-mem.db")))
    errors_file = Path(os.environ.get("ERRORS_FILE", str(CONFIG_DIR / "ERRORS.md")))

    # --- Legacy operations ---
    if not args.skip_legacy:
        if memory_dir.exists():
            rotate_memory(memory_dir, args.dry_run)

        if db_path.exists():
            archive_sessions(db_path, args.dry_run)

        if errors_file.exists():
            prune_errors(errors_file, args.dry_run)

    # --- Evolution operations (new) ---
    if db_path.exists():
        assign_quality_scores(db_path, args.dry_run)
        detect_contradictions(db_path, args.dry_run)
        expire_observations(db_path, args.dry_run)
        consolidate_observations(db_path, args.dry_run)


if __name__ == "__main__":
    main()
